[build]
  base = ""
  command = "npm install && npm run build:cuarzo"
  publish = "apps/cuarzo/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"